version: "3.7"
services:
  cryptostore:
    env_file:
      - env.s3config
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
  redisdb:
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    image: redis:6.0.8
    expose:
      - 6379
    command: ["redis-server", "--save", "''", "--appendonly", "no"]
